spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/attendance3_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootroot}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

application:
  jwt:
    header: Authorization
    prefix: Bearer

logging:
  level:
    org:
      springframework:
        security: INFO
      hibernate:
        SQL: INFO
    by:
      vsu:
        attendance: INFO